### ISSUE TITLE
Service ingress cannot be set

### ISSUE THREAD

**Issue by andrewmackett** [garbetjie/terraform-google-cloud-run#3]
At the moment the module does not allow for the ingress settings to be configured to restrict access to the Cloud Run service.
https://cloud.google.com/run/docs/securing/ingress

I've opened PR #2 to replace the `local.service_ingress` value for a variable that can be configured.

**Comment by garbetjie** [comment]
Hey @andrewmackett. My apologies, I forgot to close this issue, but I pushed changes resolving the PR in commit e366e17c015ff9e023cedc2851513c20f3b928ad.
