### ISSUE TITLE
Setup Cloud Build triggers for creation by referencing github repo instead of docker image

### ISSUE THREAD

**Issue by jdegger** [garbetjie/terraform-google-cloud-run#9]
Is this something which might be possible in the future or are there any obvious methods I'm missing to implement this with the current plugin?

**Comment by garbetjie** [comment]
I'm sure it's possible in the future.

If it becomes available for use in https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloud_run_service, then it would become available for use in this module. Until that happens, there's not much more that can be done for this module.

I'm closing this issue for now. If this changes in the future, this issue can either be re-opened, or a new one can be created.
